title: Dongjae Lee
url: "https://dongjaelee-dd2dd2.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://scholar.google.com/citations?hl=ko&user=Mr5AIPsAAAAJ"
footer_text: "Google Scholar"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "PS"
   link: "https://clist.by/coder/Dd2dD2/"
 - name: "AlLerGy"
   link: "https://allergy-knu.github.io/"
