# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Dongjae Lee
description: Bay is a minimal Jekyll Theme.
baseurl: "/"
url: "https://eliottvincent.github.io"
og_image: /assets/img/face.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
#   - name: Others

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: dongjae.lee@kangwon.ac.kr
  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/dongjae-lee-6014102b6/
    - type: github
      name: GitHub
      link: https://github.com/DongjaeLee-Dd2dD2
    - type: google
      name: Google
      link: https://scholar.google.com/citations?hl=ko&user=Mr5AIPsAAAAJ
    - type: rss
      name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
